server:
  port: 8280
  context-path: /
  

spring:
   datasource:
      driver-class-name: com.mysql.jdbc.Driver
      url: jdbc:mysql://localhost:3306/db_jxc2
      username: root
      password:
   jpa:
     hibernate.ddl-auto: update
     show-sql: true
   thymeleaf:
    cache: false